-----------------------------------INICIO DO PROCESSO  -----------------------------------

Create Database NUTRIBABY;

USE NUTRIBABY

CREATE TABLE USUARIO (
	CPF_USUARIO VARCHAR(20) NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(16) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	CEP VARCHAR(10) NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUEMRO VARCHAR(10) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL
	);


CREATE TABLE PERFIL_CRIANCA (
	ID_PERFIL_CRIANCA INT PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
	IDEDADE VARCHAR(20) NOT NULL,
	RESTICOES VARCHAR(20) NOT NULL,
	OBESERVAOES VARCHAR(20) NOT NULL,
	CPF_USUARIO VARCHAR(20) NOT NULL
	);

CREATE TABLE PEDIDOVENDA(
	ID_PEDIDO INT PRIMARY KEY NOT NULL,
	DATA DATE NOT NULL,
	QTD_PRODUTOS INT NOT NULL,
	STATUS_VENDA VARCHAR(100) NOT NULL,
	CPF_USUARIO VARCHAR(20) NOT NULL,
	CPF_ENTREGADOR VARCHAR(20) NOT NULL

	);


CREATE TABLE ENTREGADOR(
	CPF_ENTREGADOR VARCHAR(20) PRIMARY KEY,
	NOME VARCHAR(20),
	SOBRENOME VARCHAR(50),
	SALARIO DECIMAL(10,2),
	ID_PEDIDO INT NOT NULL
	);


ALTER TABLE PERFIL_CRIANCA
ADD CONSTRAINT FK_PERFIL_CRIANCA_USUARIO FOREIGN KEY (CPF_USUARIO)
REFERENCES USUARIO(CPF_USUARIO);


ALTER TABLE PEDIDOVENDA
ADD CONSTRAINT FK_PEDIDOVENDA_USUARIO FOREIGN KEY (CPF_USUARIO)
REFERENCES USUARIO(CPF_USUARIO);


ALTER TABLE PEDIDOVENDA
ADD CONSTRAINT FK_PEDIDOVENDA_ENTREGADOR FOREIGN KEY (CPF_ENTREGADOR)
REFERENCES ENTREGADOR(CPF_ENTREGADOR);


ALTER TABLE ENTREGADOR
ADD CONSTRAINT FK_ENTREGADOR_PEDIDOVENDA FOREIGN KEY (ID_PEDIDO)
REFERENCES PEDIDOVENDA(ID_PEDIDO);


-- Este comando faz o SQL Server utilizar o banco de dados criado para as próximas operações.

CREATE TABLE PEDIDOPRODUTO_INCLUI (
    ID_PRODUTO INT PRIMARY KEY,          -- Define "ID_PRODUTO" como chave primária.
	ID_PEDIDO INT,                       -- Define que "ID_PEDIDO" é um texto de até 100 caracteres e não pode ser nulo.
    QUANTIDADE INT,                      -- Define que "QUANTIDADE" é um texto de até 100 caracteres, mas pode ser nulo.
    FK_PRODUTO_ID_PROUTO INT,            -- Define uma chave estrangeira para referenciar a tabela Enderecos.
    FK_PEDIDOVENDA_ID_PEDIDO INT         -- Define uma chave estrangeira para referenciar a tabela Enderecos.
);

--DROP TABLE PEDIDOPRODUTO_INCLUI;
-- Exclui a tabela "PEDIDOPRODUTO_INCLUI" do banco de dados.

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY,          -- Define "ID_PRODUTO" como chave primária.
	COD_TIPO_PROD INT,                   -- Define "COD_TIPO_PROD" como integer.
    DESCRICAO VARCHAR (100),             -- Define que "DESCRICAO" é um texto de até 100 caracteres, mas pode ser nulo.
    NOME VARCHAR (100),                  -- Define que "NOME" é um texto de até 100 caracteres, mas pode ser nulo.
    FK_TIPO_PRODUTO_COD_TIPO_PROD INT    -- Define uma chave estrangeira para referenciar a tabela Enderecos.
);

-- TABELA PROMOCAO
CREATE TABLE PROMOCAO (
    COD_PROMOCAO INTEGER PRIMARY KEY,    -- Define "COD_PROMOCAO" como chave primária.
    NOME_CAMPANHA VARCHAR(100),          -- Define que "NOME_CAMPANHA" é um texto de até 100 caracteres, mas pode ser nulo.
    PORCENT_DESCONTO DECIMAL(5,2),       -- Define "PORCENT_DESCONTO" como a porcentagem do desconto sendo decimal.
    ID_PRODUTO INTEGER,                  -- Define "COD_TIPO_PROD" como integer.
    OBSERVACAO VARCHAR(255),             -- Define que "DESCRICAO" é um texto de até 255 caracteres, mas pode ser nulo.
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)     -- Define uma chave estrangeira para referenciar a tabela Enderecos.
); 

CREATE TABLE TIPO_PRODUTO (
    COD_TIPO_PROD INTEGER PRIMARY KEY,   -- Define "COD_TIPO_PROD" como chave primária.
    NOME_TIPO_PROD VARCHAR(100)          -- Define que "NOME_TIPO_PROD" é um texto de até 100 caracteres, mas pode ser nulo.
);

CREATE TABLE FORNECEDOR (
	CNPJ INT PRIMARY KEY,
	TELEFONE VARCHAR(20) NOT NULL,
	NOME_FANTASIA VARCHAR(100) NOT NULL,
	RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	ENDERECO VARCHAR (100) NOT NULL,
	TELEFONE_2 VARCHAR (20),
	EMAIL VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	CEP VARCHAR(10) NOT NULL,
	RUA VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(10)
)

CREATE TABLE PEDIDO_COMPRA (
	NUM_PEDIDO_FORNECEDOR INT PRIMARY KEY,
	DATA_PEDIDO DATE,
	CNPJ INT,
	STATUS VARCHAR(50)
)

-- CRIA RESTRIÇÕES - PEDIDO_COMPRA (CNPJ SE TORNA NOT NULL):
ALTER TABLE PEDIDO_COMPRA
ALTER COLUMN CNPJ INT NOT NULL

-- CRIAR FOREIGN KEY - CNPJ:
ALTER TABLE PEDIDO_COMPRA
ADD CONSTRAINT FK_FORNECEDOR_CNPJ FOREIGN KEY (CNPJ) REFERENCES FORNECEDOR(CNPJ);

CREATE TABLE PRODUTO_PEDIDOCOMPRA (
	ID_PRODUTO_PEDIDO INT PRIMARY KEY,
	DATA_COMPRA_FORNECEDOR DATE,
	QUANTIDADE INT,
	NUM_PEDIDO_FORNECEDOR INT
)

-- CRIAR FOREIGN KEY - NUM_PEDIDO_FORNECEDOR:

ALTER TABLE PRODUTO_PEDIDOCOMPRA
ADD CONSTRAINT FK_NUM_PEDIDO_FORNECEDOR FOREIGN KEY (NUM_PEDIDO_FORNECEDOR) REFERENCES PEDIDO_COMPRA(NUM_PEDIDO_FORNECEDOR);

-----------------------------------FIM DO PROCESSO -----------------------------------